import "./css/example.css";
import { AppClass } from "./AppClass";
import { Hello } from "./components/Hello";
import { HelloInDeutsch } from "./components/HelloInDeutsch";

// crating application - npx creat-react-app [name_of_the_app]
// for starting, navigate to newly created folder with command with command cd name_of_the_app
// then axecute npm start

// how to start application which is not generated by me
// navgate to the app folder, execute command npm install
// and then execute npm start

// this is a functional component
function App() {
  let number = 10;

  const element = <h1>Hello from javascript react</h1>;

  function toUpperCaseName(user) {
    return user.name.toUpperCaseName();
  }

  const student = {
    name: "Martin",
    lastName: "Trajkov",
    //image: "https://thispersondoesnotexist.com/"
  };

  function print() {
    console.log("I was clicked");
  }

  // jsx sintaksna ektenzija na javascript, no toa ne e nitu
  // javascript, nitu html no ja ima mokjta i funkcionalnostite
  // na dveta 
  // when we want to use javascript in jsx we use {} brackets

  //DOMASHNO:
  // Da kreirame funkcionalana komponenta kade vo nekoi html elementi
  // kje gi stavime nashite 3 hobia
  // a potoa da kreirame druga komponenta vo koja kje go stavite
  // omilenoto hoby

  // Da kreirame i treta komponenta kade kje imame nekoj tekst
  // koj kje bide eve slika od moeto omileno hoby
  // da ima slika od hobito
  // da stavime css vnatre da toj tekst e oboen vo nekoja razlichna boja
  // i normalno slikata d ani bide vo razmer i toj css da bide
  // importiran od nekoj nadvoreshen css file
  // koga kje pomineme so mousot vrz slikata da ispechatime vo konzola nekoj tekst (hello there!!)

  return (
    <div className="App">
      {/* <h1 className="react-hello">Hello from React!</h1> */}
      {/* <p>5+5</p> 
          <p>{ 5+5+number } result form this should be 20 </p>
          { element } */}
      { /* <h1>Hello, {toUpperCaseName(student)}</h1> */ }
      <h1>Hello, {toUpperCaseName(student)}</h1>
      <a target="blank" href="http://google.com">
        Google
      </a>
      {/*<img src={student.image} stye={{ width: 300, height: 300 }}></img> */}
      {/* <button onClick={print}>Click me</button> */}
      {/* <AppClass /> */}
      <Hello />
      <HelloInDeutsch />

    </div>
  );
}

export default App;


